mongo:
  image: mongo:3.4.2
  restart: always

backend:
  image: mavarazy/thanks-backend:latest
  restart: always
  environment:
    - APPLICATION_SECRET=T1[a`5pd?fI<E<;<QG<rUg@ZS8o6`KjuJME6Pd/[MN3nz:aBMW8v:a0lKT`Zk;bD
  links:
    - mongo

frontend:
  image: mavarazy/thank-frontend:latest
  restart: always
  ports:
    - "80:80"
  links:
    - backend