version: 2
jobs:
  build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - restore_cache:
          keys:
            - frontend-{{ checksum "yarn.lock" }}

      - run:
          name: Install packages
          command: yarn

      - run:
          name: Install parcel
          command: yarn global add parcel-bundler

      - save_cache:
          key: frontend-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          command: yarn run build-integration | yarn run build

      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS


      - run:
          name: Publish Docker image
          command: docker build -t loveit/frontend . | docker push loveit/frontend
