version: 2
jobs:
  build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - run:
          name: Fetch submodules
          command: git submodule update --init

      - restore_cache:
          keys:
            - frontend-cache-{{ checksum "yarn.lock" }}-{{ checksum "admin/yarn.lock" }}

      - run:
          name: Install packages frontend
          command: NODE_ENV=development yarn install

      - run:
          name: Install packages admin
          command: (cd admin && NODE_ENV=development yarn install)

      - run:
          name: Install parcel
          command: yarn global add parcel-bundler@1.7.0

      - save_cache:
          key: frontend-cache-{{ checksum "yarn.lock" }}-{{ checksum "admin/yarn.lock" }}
          paths:
            - node_modules
            - admin/node_modules

      - run:
          name: Build integration
          command: yarn build-integration


      - run:
          name: Build main project
          command: yarn build

      - run:
          name: Build admin
          command: (cd admin && yarn build)

      - run:
          name: Copy admin to assets
          command: cp -R admin/build/ public/admin

      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS


      - run:
          name: Create Docker image
          command: docker build -t loveit/frontend .

      - run:
          name: Push updated Docker image
          command: docker push loveit/frontend

      - run:
          name: Update Sentry Release
          command: >
            curl https://sentry.io/api/hooks/release/builtin/197694/8c2e43bf0fac4808b04256bd1ffa9f9ef6900f97d687b3a8d38e57e1042b4192/
            -X POST
            -H 'Content-Type: application/json'
            -d '{"version": "'$CIRCLE_BUILD_NUM'"}'
