version: 2
jobs:
  build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - restore_cache:
          keys:
            - frontend-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install packages
          command: NODE_ENV=development yarn install

      - run:
          name: Install parcel
          command: yarn global add parcel-bundler

      - save_cache:
          key: frontend-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Build integration
          command: yarn run build-integration


      - run:
          name: Build main project
          command: yarn run build

      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS


      - run:
          name: Create Docker image
          command: docker build -t loveit/frontend .

      - run:
          name: Push updated Docker image
          command: docker push loveit/frontend

